use super::{find_executable, ServiceDriver};
use crate::config::{
    CleanDnsSettings, HealthCheckConfig, ProbeType, ServiceInstance, ServiceSettings,
};
use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};
use tokio::process::Command;

pub struct CleanDnsDriver;

fn external_config_path(settings: &CleanDnsSettings) -> Option<&str> {
    settings
        .config_path
        .as_deref()
        .map(str::trim)
        .filter(|p| !p.is_empty())
}

fn effective_bind(instance: &ServiceInstance, settings: &CleanDnsSettings) -> String {
    let bind = settings.bind.trim();
    if bind.is_empty() {
        format!("{}:{}", instance.listen_host, instance.listen_port)
    } else {
        bind.to_string()
    }
}

fn overlay_bind_and_api(yaml: &str, bind: &str, api_port: u16) -> Result<String> {
    let mut value: serde_yaml::Value =
        serde_yaml::from_str(yaml).context("Failed to parse clean-dns YAML")?;
    let mapping = value
        .as_mapping_mut()
        .ok_or_else(|| anyhow::anyhow!("clean-dns config root must be a YAML mapping"))?;
    mapping.insert(
        serde_yaml::Value::String("bind".to_string()),
        serde_yaml::Value::String(bind.to_string()),
    );
    mapping.insert(
        serde_yaml::Value::String("api_port".to_string()),
        serde_yaml::Value::Number(serde_yaml::Number::from(u64::from(api_port))),
    );
    serde_yaml::to_string(&value).context("Failed to serialize clean-dns YAML")
}

fn write_runtime_config(dest: &Path, yaml: &str, bind: &str, api_port: u16) -> Result<()> {
    let patched = overlay_bind_and_api(yaml, bind, api_port)?;
    fs::write(dest, patched)
        .with_context(|| format!("Failed to write clean-dns config to {:?}", dest))
}

fn process_cwd(instance: &ServiceInstance, config_dir: &Path) -> PathBuf {
    if let Some(ref work_dir) = instance.work_dir {
        return PathBuf::from(work_dir);
    }
    if let ServiceSettings::CleanDns(ref s) = instance.settings {
        if let Some(path) = external_config_path(s) {
            if let Some(parent) = Path::new(path).parent().filter(|p| !p.as_os_str().is_empty()) {
                return parent.to_path_buf();
            }
        }
    }
    config_dir.to_path_buf()
}

impl ServiceDriver for CleanDnsDriver {
    fn prepare_config(&self, instance: &ServiceInstance, config_dir: &Path) -> Result<()> {
        if let ServiceSettings::CleanDns(ref s) = instance.settings {
            let dest = config_dir.join("config.yaml");
            let bind = effective_bind(instance, s);
            let api_port = s.api_port;

            if let Some(path) = external_config_path(s) {
                let config_file = Path::new(path);
                if !config_file.is_file() {
                    anyhow::bail!("clean-dns config file not found: {}", path);
                }
                let raw = fs::read_to_string(config_file)
                    .with_context(|| format!("Failed to read clean-dns config {:?}", config_file))?;
                write_runtime_config(&dest, &raw, &bind, api_port)?;
                return Ok(());
            }

            if let Some(ref raw) = s.raw_yaml {
                write_runtime_config(&dest, raw, &bind, api_port)?;
                return Ok(());
            }

            let yaml_content = format!(
                r#"# Generated by ProxyMan for clean-dns
bind: "{bind}"
api_port: {api_port}
entry: main
log:
  level: info

plugins:
  - tag: upstream_google
    type: forward
    args:
      upstreams:
        - addr: "8.8.8.8"
        - addr: "1.1.1.1"

  - tag: main
    type: sequence
    args:
      - exec: $upstream_google
"#
            );

            fs::write(&dest, yaml_content)
                .with_context(|| format!("Failed to write clean-dns config to {:?}", dest))?;
        }
        Ok(())
    }

    fn build_command(&self, instance: &ServiceInstance, config_dir: &Path) -> Result<Command> {
        let bin_path = if let Some(ref custom_bin) = instance.bin_path {
            PathBuf::from(custom_bin)
        } else {
            find_executable(
                "clean-dns",
                &[
                    "/Users/zhanghu/vpn/clean-dns/target/release/clean-dns",
                    "/Users/zhanghu/vpn/clean-dns/target/debug/clean-dns",
                    "/usr/local/bin/clean-dns",
                    "/opt/homebrew/bin/clean-dns",
                ],
            )
        };

        let config_file = config_dir.join("config.yaml");

        let mut cmd = Command::new(bin_path);
        cmd.arg("run")
            .arg("-c")
            .arg(config_file.to_string_lossy().as_ref());
        cmd.current_dir(process_cwd(instance, config_dir));

        for (k, v) in &instance.env_vars {
            cmd.env(k, v);
        }

        Ok(cmd)
    }

    fn default_health_check(&self, _instance: &ServiceInstance) -> HealthCheckConfig {
        HealthCheckConfig {
            enabled: true,
            check_interval_secs: 10,
            timeout_secs: 3,
            consecutive_failures_threshold: 3,
            probe_type: ProbeType::Dns,
            test_target: Some("one.one.one.one".to_string()),
        }
    }

    fn get_target_ports(&self, instance: &ServiceInstance, config_dir: &Path) -> Vec<super::TargetPort> {
        use crate::config::parse_host_port;
        let mut ports = Vec::new();
        let config_file = config_dir.join("config.yaml");
        let (bind, api_port) = if config_file.is_file() {
            if let Ok(content) = fs::read_to_string(&config_file) {
                if let Ok(yaml) = serde_yaml::from_str::<serde_yaml::Value>(&content) {
                    let bind = yaml.get("bind").and_then(|v| v.as_str()).map(|s| s.to_string());
                    let api_port = yaml.get("api_port").and_then(|v| v.as_u64()).map(|p| p as u16);
                    (bind, api_port)
                } else {
                    (None, None)
                }
            } else {
                (None, None)
            }
        } else {
            (None, None)
        };

        let bind_str = bind.unwrap_or_else(|| {
            if let ServiceSettings::CleanDns(ref s) = instance.settings {
                effective_bind(instance, s)
            } else {
                format!("{}:{}", instance.listen_host, instance.listen_port)
            }
        });

        if let Some((host, port)) = parse_host_port(&bind_str) {
            if port > 0 {
                // DNS service listens on UDP and TCP
                ports.push(super::TargetPort {
                    host: host.clone(),
                    port,
                    is_udp: false,
                });
                ports.push(super::TargetPort {
                    host,
                    port,
                    is_udp: true,
                });
            }
        }

        let api_p = api_port.or_else(|| {
            if let ServiceSettings::CleanDns(ref s) = instance.settings {
                Some(s.api_port)
            } else {
                None
            }
        });

        if let Some(port) = api_p {
            if port > 0 {
                ports.push(super::TargetPort {
                    host: "127.0.0.1".to_string(),
                    port,
                    is_udp: false,
                });
            }
        }

        ports
    }
}
